server:
  port: 8080

mytutor:
  jwt:
    base64-secret: aeGhbpAvxQxtq6sXeXxkKNJzDiGB8aFg1Q63rETWHX19P2iHbSUp9CvJamrNYzi+j8nvpOgn55Bn/QyCvHfDzQ==
    # 2 weeks in second
    token-validity-in-second: 1209600
  url:
    client: https://on-demand-tutor.vercel.app

vnp:
  payUrl: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  returnUrl: https://on-demand-tutor.vercel.app/confirm-payment
  tmnCode: 0ZLJX97B
  secretKey: NCG0FJ0JCPETZJBL1BZDMNPUXIEGU6CY
  version: 2.1.0
  apiUrl: https://sandbox.vnpayment.vn/merchant_webapi/api/transaction

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 6421722014-8nnqo77r774ocnq3nq72khr9u371chck.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - profile
              - email
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub

  application:
    name: MyTutor
  
  datasource:
    url: jdbc:mysql://root:hyiBSACMFZQgUvhgvkHdbVPBuIJvcUpt@monorail.proxy.rlwy.net:16440/railway?serverTimezone=Asia/Ho_Chi_Minh
    username: root
    password: hyiBSACMFZQgUvhgvkHdbVPBuIJvcUpt
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
#    username: datnguyen.dev.demo@gmail.com
#    password: "hvcj bovp bova upce"
    # test email moderator
    username: hoavo.dev.demo@gmail.com
    password: "tcsq bpbl oypv xhpt"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
